<?php

    namespace app\models;

    use Yii;
    use yii\helpers\ArrayHelper;

    /**
     * Пользователи
     *
     * @property string date
     * @property string id_tehnic
     * @property string name
     *
     * @property int id
     * @property int id_user
     *
     *
     */

    class HwAct extends ModelInterface
    {

        public static function tableName()
        {
            return 'hw_act';
        }


        public function beforeFind()
        {
            $this->username = trim($this->username);

            parent::afterFind(); // TODO: Change the autogenerated stub
        }

        public function rules()
        {
            return [
                [['date', 'id_tehnic', 'name', 'id_user'], 'required'],
                [['name','date'], 'string', 'max' => 255],
                [['id_user'], 'integer'],
                [['id_tehnic'], 'string', 'max' => 500],
            ];
        }

        public function attributeLabels()
        {
            return [
                'id' => 'ID',
                'id_tehnic' => 'Техника',
                'date' => 'Дата акта',
                'name' => 'Название акта',
                'id_user' => 'Пользователь',
            ];
        }


        public function getActNum(){

            $act = new self();
            $tehnic = new HwTehnic(['id_user' => $this->id_user]);

            $user_tehnic = array_keys(ArrayHelper::map($tehnic->getTehnicByUser(), 'id', 'id'));

            $date = strtotime('now');

            $this->date = date('Y-m-d', $date);

            $count = $this->countRecordByDate() + 1;

            $act->date = (string)$date;
            $act->id_user = $this->id_user;
            $act->id_tehnic = json_encode($user_tehnic);
            $act->name = $this->date . ' - ' . $count;
            $act->getSave();

            return $act->name;
        }

        public function countRecordByDate(){
            return self::find()
                ->where(['>=', 'date', strtotime($this->date.'00:00:00')])
                ->andWhere(['<=', 'date', strtotime($this->date.'23:59:59')])->count();
        }

    }
